//3. Write a program illustrating that all destructors for
//objects constructed in a block are called before an
//exception is thrown from that block.
#include <iostream>
using namespace std;

int main()
{

	return 0;
}
