////============================================================================
//// Name        : liveDemo.cpp
//// Author      :
//// Version     :
//// Copyright   : Your copyright notice
//// Description : Hello World in C++, Ansi-style
////============================================================================
//
//#include <iostream>
//#include <exception>
//#include <stdexcept>
//using namespace std;
//
////#include "DivideByZeroException.h"
//
////double quotient( int numerator, int denominator )
////{
////	if (denominator == 0)
////		throw DivideByZeroException();
////	return static_cast<double>(numerator)/ denominator;
////}
//
////void throwException()
////{
////	try
////	{
////		cout << " Function throwException throws an exception\n";
////		throw exception();
////	}
////	catch (exception &)
////	{
////		cout << " Exception handled in function throwException"
////		<< "\n Function throwException rethrows exception";
////		throw;
////	}
////	cout << "This also should not print\n";
////}
//
//
//
//
//
//int main() {
//
//
//
//
//
//
//
////	try
////	{
////		cout << "\nmain invokes function throwException\n";
////		throwException();
////		cout << "This should not print\n";
////	}
////	catch(exception &)
////	{
////		cout << "\n\nException handled in main\n";
////	}
////	cout << "Program control continues after catch in main\n";
//
//
//
//
////	int number1;
////	int number2;
////	double result;
////	cout << "Enter two integers (end-of-file to end): ";
////	while (cin >> number1 >> number2)
////	{
////		try
////		{
////			result = quotient(number1,number2);
////			cout <<"The quotient is: " << result << endl;
////		}
////		catch (DivideByZeroException &divideByZeroException)
////		{
////			cout << "Exception occurred: "
////					<< divideByZeroException.what() << endl;
////		}
////		cout << "\nEnter two integers (end-of-file to end): ";
////	}
////	cout << endl;
//
//
//	return 0;
//}
